sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t himzei/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI-true himzei/docker-react-app npm run tet -- --coverage

after_success:
  - echo "Test Success"
